# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InfiniteCollectionView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InfiniteCollectionView
  pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'

end
