# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmDatabase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealmDatabase
  pod 'RealmSwift', '2.4.2'
end
