# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bowties' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bowties
  pod 'RealmSwift', '2.5.0'
  pod 'SwiftyJSON', '3.1.4'

end
