# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlamofireWithXML' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlamofireWithXML
  pod 'Alamofire', '4.3.0'
  pod 'AlamofireImage', '3.1'
  pod 'SWXMLHash', '3.0.4'
end
