# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'RealmStarted' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealmStarted
pod 'RealmSwift', '0.98.0'
pod 'Firebase/Core'
pod 'Firebase/Crash'
pod 'QuadratTouch', '>= 1.0'
pod 'Firebase/Auth'
end
