# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'AlamofireDemo' do
 pod 'ObjectMapper', '1.1.5'
 pod 'Alamofire', '3.4.1'
 pod 'RealmSwift', '0.98.6'
end

